### ISSUE TITLE
Implement message values

### ISSUE THREAD

**Issue by Zarquan** [ivoa/Calycopis-broker#125]
Add the map of name->value pairs to the messages.

**Comment by Zarquan** [comment]
```
....
messages:
  - type: "urn:resource-limit"
    time: "2025-02-10T15:09:18.516996Z"
    level: "WARN"
    template: "Minimum memory exceeds available resources [${resource}][${memory}][${limit}]"
  - type: "urn:resource-limit"
    time: "2025-02-10T15:09:18.517038Z"
    level: "WARN"
    template: "Maximum memory exceeds available resources [${resource}][${memory}][${limit}]"
result: "YES"
....
```
