### ISSUE TITLE
Fail request if memory is too high

### ISSUE THREAD

**Issue by Zarquan** [ivoa/Calycopis-broker#126]
Asking for too much memory doesn't cause it to answer NO.
```
....
messages:
  - type: "urn:resource-limit"
    time: "2025-02-10T15:09:18.516996Z"
    level: "WARN"
    template: "Minimum memory exceeds available resources [${resource}][${memory}][${limit}]"
  - type: "urn:resource-limit"
    time: "2025-02-10T15:09:18.517038Z"
    level: "WARN"
    template: "Maximum memory exceeds available resources [${resource}][${memory}][${limit}]"
result: "YES"
....
```
