### ISSUE TITLE
Add hard coded preparing and releasing durations

### ISSUE THREAD

**Issue by Zarquan** [ivoa/Calycopis-broker#128]
Add hard coded preparing and releasing durations to demonstrate how they are handled in the model.
```
    schedule:
      preparing:
        duration: "PT10M"
        start: "2025-02-11T11:20:00Z"
      executing:
        duration: "PT1H"
        start: "2025-02-11T11:30:00Z"
      releasing:
        duration: "PT5M"
        start: "2025-02-11T12:30:00Z"

```
