### ISSUE TITLE
Do we add minimal to the offered values ?

### ISSUE THREAD

**Issue by Zarquan** [ivoa/Calycopis-broker#129]
Do we add a minimal flag to the offered values to help the client find the minimal ones ?
```
  cores:
    ....
    offered:
      minimal: true
      min: 10
      max: 10
  memory:
    ....
    offered:
      minimal: true
      min: 6
      max: 6
```
