### ISSUE TITLE
Modify generated classes

### ISSUE THREAD

**Issue by Zarquan** [ivoa/Calycopis-broker#148]
This issue is aimed at finding a solution to #69 

See if we can split the processing for `calycopis-openapi` into separate steps.
1. Generate the sources, pause to modify them, and then compile them.
1. Giving us time to experiment with removing the `JsonIgnoreProperties` from `IvoaAbstractComputeResource`.
1. See if this fixes the `IvoaSimpleComputeResource` type problem.

```
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
```

**Comment by Zarquan** [comment]
Adding this property to the Maven project file skips code generation if the source hasn't changed.

```
<plugin>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <version>7.6.0</version>
    <executions>
        <execution>
            ....
            <configuration>
                <skipIfSpecIsUnchanged>true</skipIfSpecIsUnchanged>
```

Which gives us a chance to comment out the the `@JsonIgnoreProperties` annotation in `IvoaAbstractComputeResource`.

```
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
```

Which results in two `type` values in the output, the right one and the wrong one.
```
resources:
  compute:
    - type: "SimpleComputeResourceBean"
      uuid: "8894f76f-2921-4418-9724-3d3358248f2c"
      name: "computer-001"
      type: "https://www.purl.org/ivoa.net/EB/schema/types/resources/compute/simple-compute-resource-1.0"
      ....
```

Not fixed yet, but this is a step in the right direction.
