### ISSUE TITLE
Explore multiple repositories for a docker container

### ISSUE THREAD

**Issue by Zarquan** [ivoa/Calycopis-broker#166]
Explore multiple repositories for a docker container, verified using the digest.

**Comment by Zarquan** [comment]
Rationale for this is that SRCNet may have the same software in more than one Docker image repository.

The best place to decide which repository to use is at the local node level. Individual ExecutionBroker services will 'know' which is their 'local' repository, and can use past history to estimate which remote repository would be the best one to use. 

So we need to pass the list of options down to the local level services.

Simple change the data model - make repository an array. This assumes that the namespace, name, and tags are all the same.
```
executable:
  type:  "https://www.purl.org/ivoa.net/EB/schema/types/executables/docker-container-1.0"
  name:  "calycopis-broker"
  namespace: "ivoa/calycopis"
  tag: "2025.03.12"
  digest: "sha256:1d3a2c07fa90532a9090a8d05057c0058d25d11656e3e89f53a5769a6a06dfc0"
  platform: 
    architecture: "amd64"
    os: "linux"
  # Multiple locations, with the same name, namespace and tag.
  repositories:
    - "ghcr.io"
    - "harbor.INSRC.ac.in"
    - "UKSRC-repo.ac.uk"
```

A more complex change to the data model, add another level called `replicas` to the structure allowing different names, namespaces and tags at different locations.

```
executable:
  type:  "https://www.purl.org/ivoa.net/EB/schema/types/executables/docker-container-1.0"
  platform: 
    architecture: "amd64"
    os: "linux"
  digest: "sha256:1d3a2c07fa90532a9090a8d05057c0058d25d11656e3e89f53a5769a6a06dfc0"
  # Multiple locations, with different names, namespaces and tags.
  replicas:
    - name:  "calycopis-broker"
      namespace: "ivoa/calycopis"
      tag: "2025.03.12"
      repository: "ghcr.io"

    - name:  "calycopis-broker"
      namespace: "ivoa/calycopis"
      tag: "2025.03.12"
      repository: "harbor.INSRC.ac.in"

    - name:  "calycopis-broker"
      namespace: "ivoa/calycopis"
      tag: "2025.03.12"
      repository: "UKSRC-repo.ac.uk"
```

The unique key to make sure we get the right object is always the sha256 digest, not the name or tag. In which case, can all of the other fields be optional ? We just need the digest and the repository hostname.
```
executable:
  type:  "https://www.purl.org/ivoa.net/EB/schema/types/executables/docker-container-1.0"
  platform: 
    architecture: "amd64"
    os: "linux"
  digest: "sha256:1d3a2c07fa90532a9090a8d05057c0058d25d11656e3e89f53a5769a6a06dfc0"
  # Multiple respositories.
  replicas:
    - repository: "ghcr.io"
    - repository: "harbor.INSRC.ac.in"
    - repository: "UKSRC-repo.ac.uk"
```

Bring both together, and the top level can specify name, namespace, and tag, and the replicas can override them of they need to.
```
executable:
  type:  "https://www.purl.org/ivoa.net/EB/schema/types/executables/docker-container-1.0"
  platform: 
    architecture: "amd64"
    os: "linux"
  name:  "calycopis-broker"
  namespace: "ivoa/calycopis"
  tag: "2025.03.12"
  digest: "sha256:1d3a2c07fa90532a9090a8d05057c0058d25d11656e3e89f53a5769a6a06dfc0"
  # Multiple locations, with different names, namespaces and tags.
  replicas:
    - name:  "calycopis-broker-21"
      repository: "ghcr.io"

    - repository: "harbor.INSRC.ac.in"

    - tag: "2025.03.12-002"
      repository: "UKSRC-repo.ac.uk"
```

Or, get rid of the separate parts (name, namespace, and tag) and just have a list of identifiers.
```
executable:
  type:  "https://www.purl.org/ivoa.net/EB/schema/types/executables/docker-container-1.0"
  platform: 
    architecture: "amd64"
    os: "linux"
  digest: "sha256:1d3a2c07fa90532a9090a8d05057c0058d25d11656e3e89f53a5769a6a06dfc0"
  # Multiple locations.
  replicas:
    - "ghcr.io/ivoa/calycopis/calycopis-broker-21:2025.03.12"
    - "harbor.INSRC.ac.in/ivoa/calycopis/calycopis-broker-21:2025.03.12"
    - "UKSRC-repo.ac.uk/ivoa/calycopis/calycopis-broker-21:2025.03.12-002"
```
