### ISSUE TITLE
Same compute resource twice, with no details

### ISSUE THREAD

**Issue by Zarquan** [ivoa/Calycopis-broker#187]
Something broken .. we get the same compute resource twice, with no details.
```
resources:
  compute:
    - type: "https://www.purl.org/ivoa.net/EB/schema/types/resources/compute/simple-compute-resource-1.0"
      uuid: "a6a697fc-20a4-44a0-b978-19d485b4b0ea"
    - type: "https://www.purl.org/ivoa.net/EB/schema/types/resources/compute/simple-compute-resource-1.0"
      uuid: "a6a697fc-20a4-44a0-b978-19d485b4b0ea"

```

**Comment by Zarquan** [comment]
The duplication is only in the initial response.
Requesting the offerset from the database only returns a single resource, but still no details.
```
resources:
  compute:
  - type: "https://www.purl.org/ivoa.net/EB/schema/types/resources/compute/simple-compute-resource-1.0"
    uuid: "99c96378-9048-4267-bc2b-fc3f6329f55e"

```
