### ISSUE TITLE
Link between executable and compute

### ISSUE THREAD

**Issue by Zarquan** [ivoa/Calycopis-broker#188]
Lots of questions ..

We have one executable and multiple compute resources.
Does that mean we have one executable on one of the compute resources, and nothing on the others ?
Or do we run the executable on all of the compute resources ?
If the latter, which one is in control ?

If we add a 'deploy' or 'compute' reference from the executable to one of the compute resources, what goes on the other compute resources ?

If we support more than one executable, we are getting into docker-compose or Helm chart territory.
Don't re-invent the wheel.

If we have one docker-compose executable, does that get deployed on a single compute resource ?
If not then how are the docker-compose components distributed across the compute resources ?

If we have a Helm chart executable, does this get deployed on a generic-compute resource or a Kubernetes-compute resource ?
Does a  Kubernetes-compute resource contain a set of generic-compute resources ?

We need some real world use cases that need multiple  compute resources.
We need some real world use cases that need GPUs.

**Comment by Zarquan** [comment]
Initially this is a OneToMany relationship.
An executable has a list of computers it is installed on.
```
executable:
  name: docker-container-001
  ....
  computers:
    - computer-001
    - computer-002

resources:
  compute:
    - name: computer-001
      ....
    - name: computer-002
      ....
```

If/when we have multiple executables, then this becomes a ManyToMany relationship.
```
executables:
  - name: docker-container-001
    ....
    computers:
      - computer-001
      - computer-002

resources:
  compute:
    - name: computer-001
      ....
      executables:
        - docker-container-001
```
Users only need to speficy one shide of the relationship and the verification layer will connect the other side automatically.
