### ISSUE TITLE
Importable schema element for SoftwareDiscovery

### ISSUE THREAD

**Issue by Zarquan** [ivoa/Calycopis-broker#195]
The data model for SoftwareDiscovery contains a lot of similar components to the ExecutionBroker data model. Ideally, the description of the executable and the resources it needs should use same structure as the components in the ExecutionBroker data model.

To make this easier to manage, we should create an element in the ExecutionBroker data model that can be imported directly into the SoftwareDiscovery data model.

```
DiscoveryExecutionBlock:
  description: >
    The ExecutionBroker elements to be imported into the SoftwareDiscovery data model.
  type: object
  title: DiscoveryExecutionBlock
  properties:
    name:
      description: >
        A human readable name.
      type: string
    executable:
      description: >
        A description of the executable software component.
      $ref: 'AbstractExecutable'
    resources:
      description: >
        A list of the compute, storage and data resources it needs.
      $ref: 'ExecutionResourceList'
```
