### ISSUE TITLE
Add multiple locations to simple download

### ISSUE THREAD

**Issue by Zarquan** [ivoa/Calycopis-broker#204]
Change the single `location` to an array of strings.

https://github.com/ivoa/Calycopis-broker/blob/fc57173d40e80c25717bcf682a8eee1265850a82/openapi/ivoa/types/resources/data/simple-data-resource-1.0.yaml#L48-L51

becomes

```
        locations:
          description: |
            A list of URLs to download the data from.
          array:
            items:
              type: string
```
This allows the Execution Broker to decide which source to use based on historical data.
