### ISSUE TITLE
Crazy thought - make compote resource singular

### ISSUE THREAD

**Issue by Zarquan** [ivoa/Calycopis-broker#206]
Move compute resources out of the rersources list and make it a single instance sibling of executable.

So this:
```
executable:
  name: docker-container-001
  ....

resources:
  compute:
    - name: compute-resource-001
      ....
  data:
    - name data-resource-001
```

becomes this
```
executable:
  name: docker-container-001
    ....
computer:
  name: compute-resource-001
    ....

resources:
      ....
  data:
    - name data-resource-001
      ....
    - name data-resource-001
      ....
```

This solves all the worry about how to describe which compute resource an executable is deployed on. see #188 

We then define new types of compute resources for different types of clusters, like `kubernetes-cluster` and `dask-cluster` which can include definitions of their internal nodes.

```
executable:
  name: docker-container-001
    ....
computer:
  name: compute-resource-001
  type: ..../dask-cluster
  ....
  nodes:
    - name: head-node
      cores: ..
      memory: ..
    - name: worker-node
      cores: ..
      memory: ..
      replicas: 27
          
resources:
      ....
  data:
    - name data-resource-001
      ....
    - name data-resource-001
      ....
```
