### ISSUE TITLE
Define the relationship between data resource and storage resource

### ISSUE THREAD

**Issue by Zarquan** [ivoa/Calycopis-broker#211]
A data resource is allocated to one storage resource.
A storage resource may contain many data resources.

```
resources:
  data:
    - name: data-001
      ....
      storage: storage-001

    - name: data-002
      ....
      storage: storage-001

    - name: data-003
      ....
      storage: storage-003

  storage:
    - name: storage-001
      ....
      data:
        - storage-001
        - storage-002
  
    - name: storage-003
      ....
      data:
        - storage-003
```
