### ISSUE TITLE
Add an incrementing number to offer name

### ISSUE THREAD

**Issue by Zarquan** [ivoa/Calycopis-broker#222]
At the moment, offers are given a default  'no-name' name.
Better to add a number to the end of the request name.
```
uuid: "f63d802f-4e44-4192-8cc1-7aa53b1c6600"
name: "example-009"
type: "https://www.purl.org/ivoa.net/EB/schema/types/offersets/offerset-response-1.0"
....
offers:
  - uuid: "ced11365-95ff-493f-95ae-3ddafc54ae9c"
    name: "no name"
    type: "https://www.purl.org/ivoa.net/EB/schema/types/sessions/execution-session-response-1.0"
    ....
  - uuid: "1211b4bc-2052-4e58-bf58-f73fe2ca4565"
    name: "no name"
    type: "https://www.purl.org/ivoa.net/EB/schema/types/sessions/execution-session-response-1.0"
    ....
```
becomes
```
uuid: "f63d802f-4e44-4192-8cc1-7aa53b1c6600"
name: "example-009"
type: "https://www.purl.org/ivoa.net/EB/schema/types/offersets/offerset-response-1.0"
....
offers:
  - uuid: "ced11365-95ff-493f-95ae-3ddafc54ae9c"
    name: "example-009-001"
    type: "https://www.purl.org/ivoa.net/EB/schema/types/sessions/execution-session-response-1.0"
    ....
  - uuid: "1211b4bc-2052-4e58-bf58-f73fe2ca4565"
    name: "example-009-002"
    type: "https://www.purl.org/ivoa.net/EB/schema/types/sessions/execution-session-response-1.0"
    ....
```
