### ISSUE TITLE
Add structure to error messages

### ISSUE THREAD

**Issue by Zarquan** [ivoa/Calycopis-broker#39]
....

**Comment by Zarquan** [comment]
Fixed in #51

**Comment by Zarquan** [comment]
Done
```
messages:
  - type: "urn:debug"
    time: "2024-10-14T06:07:59.621642454Z"
    level: "DEBUG"
    template: "OfferSetEntity select(UUID)"
```
