### ISSUE TITLE
Restore min/max for cores and memory

### ISSUE THREAD

**Issue by Zarquan** [ivoa/Calycopis-broker#77]
Separate the `requested` and `offered` values for the `generic-compute` cores and memory and restore the min/max values for the `requested` set.
```
resources:
  compute:
  - type: uri:generic-compute
    cores:
      requested:
        min: 4
        max: 8
    memory:
      requested:
        min: 16
        max: 24
        units: GiB
```

New rational -  if/when the service offers more resources than requested, the user can specify a max value on some nodes to shift the extra allocation to other modes.
