### ISSUE TITLE
Implement max constraints for cores and memory 

### ISSUE THREAD

**Issue by Zarquan** [ivoa/Calycopis-broker#92]
The current prototype doesn't take into account the max constraint for cores and memory.
```
resources:
    compute:
      - type: "SimpleComputeResourceBean"
        cores:
          requested:
            min: 6
            max: 6
          offered:
            min: 12
            max: 12
```
